# Generated by Django 4.2.9 on 2024-05-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("team", models.CharField(max_length=100)),
                ("total_goals", models.IntegerField(default=False)),
                ("total_assists", models.IntegerField(default=False)),
                ("market_value", models.CharField(max_length=200)),
            ],
        ),
    ]
