# Generated by Django 4.2.9 on 2024-05-15 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("player_app", "0002_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
    ]
