# Generated by Django 4.2.13 on 2024-05-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_app", "0003_delete_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
    ]
