# Generated by Django 4.2.13 on 2024-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_app", "0004_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("top_winner", models.IntegerField(default=False)),
            ],
        ),
    ]
