# Generated by Django 4.2.13 on 2024-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_app", "0005_competition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="top_winner",
            field=models.CharField(max_length=100),
        ),
    ]
