# Generated by Django 4.2.13 on 2024-05-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("player_app", "0006_alter_competition_top_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="top_winner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="player_app.team",
            ),
        ),
    ]
