# Generated by Django 4.2.13 on 2024-05-28 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("player_app", "0007_alter_competition_top_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="top_winner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitions",
                to="player_app.team",
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["total_goals"], name="player_app__total_g_30816d_idx"
            ),
        ),
    ]
