# Generated by Django 4.2.13 on 2024-05-30 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("player_app", "0008_alter_competition_top_winner_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Player",
        ),
    ]
