# Generated by Django 4.2.13 on 2024-05-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_app", "0009_delete_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("team", models.CharField(max_length=100)),
                ("total_goals", models.IntegerField(db_index=True, default=False)),
                ("total_assists", models.IntegerField(db_index=True, default=False)),
                ("market_value", models.CharField(max_length=200)),
            ],
        ),
    ]
