# Generated by Django 4.2.13 on 2024-06-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_app", "0011_alter_player_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="market_value",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="team",
            name="country",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
