import csv

# List of real soccer teams and their countries
teams = [
    {"name": "Manchester United", "country": "England"},
    {"name": "Real Madrid", "country": "Spain"},
    {"name": "Barcelona", "country": "Spain"},
    {"name": "Bayern Munich", "country": "Germany"},
    {"name": "Paris Saint-Germain", "country": "France"},
    {"name": "Juventus", "country": "Italy"},
    {"name": "Chelsea", "country": "England"},
    {"name": "Liverpool", "country": "England"},
    {"name": "Manchester City", "country": "England"},
    {"name": "Arsenal", "country": "England"},
    {"name": "Tottenham Hotspur", "country": "England"},
    {"name": "Borussia Dortmund", "country": "Germany"},
    {"name": "AC Milan", "country": "Italy"},
    {"name": "Inter Milan", "country": "Italy"},
    {"name": "Atletico Madrid", "country": "Spain"},
    {"name": "Sevilla", "country": "Spain"},
    {"name": "AS Roma", "country": "Italy"},
    {"name": "Napoli", "country": "Italy"},
    {"name": "Lazio", "country": "Italy"},
    {"name": "RB Leipzig", "country": "Germany"},
    {"name": "Ajax", "country": "Netherlands"},
    {"name": "Porto", "country": "Portugal"},
    {"name": "Benfica", "country": "Portugal"},
    {"name": "Sporting CP", "country": "Portugal"},
    {"name": "PSV Eindhoven", "country": "Netherlands"},
    {"name": "Feyenoord", "country": "Netherlands"},
    {"name": "Galatasaray", "country": "Turkey"},
    {"name": "Fenerbahçe", "country": "Turkey"},
    {"name": "Besiktas", "country": "Turkey"},
    {"name": "Celtic", "country": "Scotland"},
    {"name": "Rangers", "country": "Scotland"},
    {"name": "Olympique Lyonnais", "country": "France"},
    {"name": "Marseille", "country": "France"},
    {"name": "Monaco", "country": "France"},
    {"name": "Anderlecht", "country": "Belgium"},
    {"name": "Club Brugge", "country": "Belgium"},
    {"name": "Standard Liege", "country": "Belgium"},
    {"name": "Shakhtar Donetsk", "country": "Ukraine"},
    {"name": "Dynamo Kyiv", "country": "Ukraine"},
    {"name": "Zenit St Petersburg", "country": "Russia"},
    {"name": "Spartak Moscow", "country": "Russia"},
    {"name": "CSKA Moscow", "country": "Russia"},
    {"name": "Boca Juniors", "country": "Argentina"},
    {"name": "River Plate", "country": "Argentina"},
    {"name": "Santos", "country": "Brazil"},
    {"name": "Flamengo", "country": "Brazil"},
    {"name": "Palmeiras", "country": "Brazil"},
    {"name": "Corinthians", "country": "Brazil"},
    {"name": "São Paulo", "country": "Brazil"},
    {"name": "Grêmio", "country": "Brazil"},
    {"name": "Internacional", "country": "Brazil"},
    {"name": "Cruzeiro", "country": "Brazil"},
    {"name": "Atletico Mineiro", "country": "Brazil"},
    {"name": "Vasco da Gama", "country": "Brazil"},
    {"name": "America de Cali", "country": "Colombia"},
    {"name": "Atletico Nacional", "country": "Colombia"},
    {"name": "Millonarios", "country": "Colombia"},
    {"name": "Pachuca", "country": "Mexico"},
    {"name": "Club America", "country": "Mexico"},
    {"name": "Chivas", "country": "Mexico"},
    {"name": "Cruz Azul", "country": "Mexico"},
    {"name": "Pumas UNAM", "country": "Mexico"},
    {"name": "Tigres UANL", "country": "Mexico"},
    {"name": "Monterrey", "country": "Mexico"},
    {"name": "Al Ahly", "country": "Egypt"},
    {"name": "Zamalek", "country": "Egypt"},
    {"name": "Esperance", "country": "Tunisia"},
    {"name": "Raja Casablanca", "country": "Morocco"},
    {"name": "Wydad Casablanca", "country": "Morocco"},
    {"name": "Kaizer Chiefs", "country": "South Africa"},
    {"name": "Orlando Pirates", "country": "South Africa"},
    {"name": "Sundowns", "country": "South Africa"},
    {"name": "Al Hilal", "country": "Saudi Arabia"},
    {"name": "Al Nassr", "country": "Saudi Arabia"},
    {"name": "Al Ittihad", "country": "Saudi Arabia"},
    {"name": "Al Ain", "country": "United Arab Emirates"},
    {"name": "Al Jazira", "country": "United Arab Emirates"},
    {"name": "Al Sadd", "country": "Qatar"},
    {"name": "Al Duhail", "country": "Qatar"},
    {"name": "Persepolis", "country": "Iran"},
    {"name": "Esteghlal", "country": "Iran"},
    {"name": "Kawasaki Frontale", "country": "Japan"},
    {"name": "Urawa Red Diamonds", "country": "Japan"},
    {"name": "Yokohama F. Marinos", "country": "Japan"},
    {"name": "Gamba Osaka", "country": "Japan"},
    {"name": "FC Seoul", "country": "South Korea"},
    {"name": "Jeonbuk Hyundai Motors", "country": "South Korea"},
    {"name": "Suwon Samsung Bluewings", "country": "South Korea"},
    {"name": "Sydney FC", "country": "Australia"},
    {"name": "Melbourne Victory", "country": "Australia"},
    {"name": "Perth Glory", "country": "Australia"},
    {"name": "Wellington Phoenix", "country": "New Zealand"},
    {"name": "Club Libertad", "country": "Paraguay"},
    {"name": "Olimpia", "country": "Paraguay"},
    {"name": "Nacional", "country": "Uruguay"},
    {"name": "Penarol", "country": "Uruguay"},
    {"name": "Colo Colo", "country": "Chile"},
    {"name": "Universidad de Chile", "country": "Chile"},
    {"name": "Universidad Catolica", "country": "Chile"},
    {"name": "Sporting Cristal", "country": "Peru"},
    {"name": "Alianza Lima", "country": "Peru"},
    {"name": "Bolivar", "country": "Bolivia"},
    {"name": "The Strongest", "country": "Bolivia"}
    # Add more teams to reach 1000 entries
]

# Write data to CSV
csv_file = "soccer_teams.csv"
csv_columns = ["name", "country"]

try:
    with open(csv_file, 'w', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=csv_columns)
        writer.writeheader()
        for data in teams:
            writer.writerow(data)
except IOError:
    print("I/O error")

print(f"{csv_file} has been created with real soccer teams.")
